config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home', to: 'pages#home'
  
  resources :recipes

  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]

  get '/login', to: 'sessions#new'
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :chefname, presence: true, length: {maximum:30}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: { case_sensitive: false }
    has_many :recipes, dependent: :destroy
    has_secure_password 
    validates :password, presence: true, length: {minimum: 5}, allow_nil: true
end  

app/models/recipe.rb
class Recipe < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true, length: {minimum: 5, maximum: 500} 
    belongs_to :chef
    validates :chef_id, presence: true
    default_scope -> {order(updated_at: :desc)} 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base 
    helper_method :current_chef, :logged_in?

    def current_chef
    @current_chef ||= Chef.find(session[:chef_id]) if session[:chef_id]
    end
    
    def logged_in?
    !!current_chef
    end
    
    def require_user
    if !logged_in?
    flash[:danger] = "You must be logged in to perform that action"
    redirect_to root_path
    end
    end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
    
    before_action :set_chef, only: [:show, :edit, :update, :destroy]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    before_action :require_admin, only: [:destroy]
    
    def index
        @chefs = Chef.paginate(page: params[:page], per_page: 5)
    end
    
    def new
        @chef = Chef.new 
    end
    def create
        @chef = Chef.new(chef_params)
        if @chef.save
            session[:chef_id] = @chef.id
            flash[:success] = "Welcome #{@chef.chefname} to Myrecipes App!"
            redirect_to chef_path(@chef)
        else
            render 'new'
        end
    end

    def show
        @chef_recipes = @chef.recipes.paginate(page: params[:page], per_page: 5)
    end

    def edit
    end

    def update
        if @chef.update(chef_params)
            flash[:success] = "Your account was update successfully"
            redirect_to @chef
        else
            render 'edit'
        end
    end

    def destroy 
        if !@chef.admin?
            @chef.destroy
            flash[:danger] = "Chef and all associated recipes have been deleted"
            redirect_to chefs_path
        end
    end 

    private 
        def chef_params 
            params.require(:chef).permit(:chefname, :email, :password, :password_confirmation)
        end

        def set_chef 
            @chef = Chef.find(params[:id]) 
        end

        def require_same_user
            if current_chef != @chef && !current_chef.admin?
                flash[:danger] = "You can only edit or delete your own account"
                redirect_to chefs_path
            end
        end

        def require_admin
            if logged_in? and !current_chef.admin?
                flash[:danger] = "Only admin users can perform that action"
                redirect_to root_path
            end
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to recipes_path if logged_in?
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :set_recipe, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    def index
        @recipes = Recipe.paginate(page: params[:page], per_page: 5)
    end

    def show
    end

    def new
        @recipe = Recipe.new
    end

    def create
        @recipe = Recipe.new(recipe_params)
        @recipe.chef = current_chef
        if @recipe.save
            flash[:success] = 'Recipe was created successfully'
            redirect_to recipe_path(@recipe)
        else
            render 'new'
        end

    end

    def edit
    end
    
    def update
        if @recipe.update(recipe_params)
            flash[:success] = "Recipe was updated successfully!"
            redirect_to recipe_path(@recipe)
        else
            render 'edit'
        end
    end

    def destroy
        @recipe = Recipe.find(params[:id]).destroy
        flash[:success] = "Recipe deleted successfully"
        redirect_to recipes_path
    end

    private
        def set_recipe
            @recipe = Recipe.find(params[:id])
        end
        
        def recipe_params
            params.require(:recipe).permit(:name, :description)
        end

        def require_same_user
            if current_chef != @recipe.chef and !current_chef.admin?
            flash[:danger] = "You can only edit or delete your own recipes"
            redirect_to recipe_path
            end
        end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
    def new
    # will simply render the form
    end
  
    def create
        chef = Chef.find_by(email: params[:session][:email].downcase)
        if chef && chef.authenticate(params[:session][:password])
            session[:chef_id] = chef.id
            flash[:success] = "You have successfully logged in"
            redirect_to chef
        else
            flash.now[:danger] = "There was something wrong with your authentication"
            render 'new'
        end
    end
  
    def destroy
        session[:chef_id]=nil
        flash[:success]="You have logged out"
        redirect_to root_path
    end
  
end 

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options={size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.chefname, class: "img-circle")
    end
end

app/views/chefs/_form.html.erb
<%= render 'shared/errors', obj: @chef %>
<div class="row">
    <div class="col-md-12">
        <%= form_for(@chef, :html => {class: "form-horizontal", role: "form"}) do |f|%>
            <div class="form-group">
                <div class="control-label col-md-2">
                    <%= f.label :chefname %>
                </div>
                <div class="col-md-8">
                    <%= f.text_field :chefname, class:"form-control", placeholder: "Enter your username", autofocus: true%>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-2">
                    <%= f.label :email%>
                </div>
                <div class="col-md-8">
                    <%= f.email_field :email, class:"form-control", placeholder:"Enter your email"%>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-2">
                    <%= f.label :password%>
                </div>
                <div class="col-md-8">
                    <%= f.password_field :password, class:"form-control", placeholder:"Choose a password"%>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-2">
                    <%= f.label :password_confirmation, "Confirm Password"%>
                </div>
                <div class="col-md-8">
                    <%= f.password_field :password_confirmation, class:"form-control", placeholder:"Confirm your password"%>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <%= f.submit(@chef.new_record? ? "Sign up" : "Update my account",
                    class:"btn btn-primary btn-lg btn-danger")%>
                </div>
            </div>
        <%end%>
        <div class="col-md-4 col-md-offset-4">
            [<%= link_to "Cancel request and return to recipes listing",recipes_path %>]
        </div>
    </div>
</div>

app/views/chefs/edit.html.erb
<%= render 'shared/page_title', title: "Edit your profile"%>
<%= render 'form'%>

app/views/chefs/index.html.erb
<%= render 'shared/page_title', title: "Showing all chefs"%>
<div align="center">
    <%= will_paginate @chefs, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer%>
    <% @chefs.each do |chef| %>
        <ul class="listing">
            <div class="row">
                <div class="card bg-light col-md-4 col-md-offset-4">
                    <li><%= link_to gravatar_for(chef), chef_path(chef)%></li>
                    <li class="chef-title"><%= link_to chef.chefname.capitalize, (chef_path(chef))%></li>
                    <li><small> <%= pluralize(chef.recipes.count, "recipe") if chef.recipes%> </small></li>
                    <% if logged_in? && current_chef.admin? && !chef.admin?%>
                        <li> <%= link_to "Delete this chef", chef_path(chef), method: :delete, 
                                    data: {confirm: "Are you sure you want to delete the chef and all associated recipes?"} %> </li>
                    <% end %>
                </div>
            </div>
        </ul>
    <% end %>
    <%= will_paginate @chefs, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer%>
</div>

app/views/chefs/new.html.erb
<%= render 'shared/page_title', title: "Sign up for the application"%>
<%= render 'form'%>

app/views/chefs/show.html.erb
<%= render 'shared/page_title', title: "Chef #{@chef.chefname}'s profile"%>
<div class = "row ">
    <div class="col-md-4 col-md-offset-4 center" style="margin: 0 42%">
        <%= gravatar_for @chef, size:150%>
    </div>
</div>
<h4 align="center"> <%= @chef.chefname%>'s recipes </h4>
<div class= "d-flex justify-content-center">
    <%= will_paginate @chef_recipes, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer%>
</div>
<%= render 'recipes/recipe', obj: @chef_recipes %>
<div class= "d-flex justify-content-center">
    <%= will_paginate @chef_recipes, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer %>
</div>

app/views/layouts/_footer.html.erb
 <footer class="text-muted">
    <div class="container-fluid">
    <p class="float-right">
        <a href="#">Back to top</a>
    </p>
    <p>MyRecipes feito por Ruy com &copy; Bootstrap, but please download and customize it for yourself!</p>
    <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting started guide</a>.</p>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="row justify-content-center" style="width: 100vw">
    <div class="col-md-10 col-md-offset-1">
        <% flash.each do |name, msg|%>
            <div class="alert alert-<%=name %>">
                <a href"#" class="close" data-dismiss="alert">&#215;</a>
                <%= msg%>
            </div>
        <% end %>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'MyRecipes', root_path, class: "navbar-brand", id: "logo"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%=chefs_path%>">Chefs<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link"href="<%=recipes_path%>">All recipes</a>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Recipes
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="<%=new_recipe_path%>"> Create new recipe </a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
      <% end %>
      <li class="nav-item">
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-light my-2 my-sm-0" type="submit">Search</button>
        </form>
      </li>
    </ul>
    <ul class="navbar-nav mr-md-5">
      <%if logged_in? %>
      <div class="dropdown">
        <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         <%= current_chef.chefname.capitalize %>'s Profile <%= "Admin" if current_chef.admin?%>
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
          <button class="dropdown-item" type="button"><%= link_to "View your profile", chef_path(current_chef) %></button>
          <button class="dropdown-item" type="button"><%= link_to "Edit your profile", edit_chef_path(current_chef) %></button>
          <div class="dropdown-divider"></div>
          <button class="dropdown-item" type="button"><%= link_to "Log out", logout_path, method: :delete %></button>
        </div>
      </div>
      <% else %>
      <li class="nav-item">
          <a class="btn btn-outline-success my-2 my-sm-0 text-success nav-link" href="<%=login_path%>">Log in</a>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrecipes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navigation'%>
  <%= render 'layouts/messages'%>
  <div class = 'container'>
     <%= yield %>
  </div>
  <%= render 'layouts/footer'%>
  </body>
</html>

app/views/pages/home.html.erb
<div class='jumbotron center'>
    <h1 font-s>Welcome to MyRecipes</h1>
    <h2>The best recipes app!</h2>
    <p> <%= link_to 'Sign up', signup_path, class: 'btn btn-danger btn-lg'%> </p>
</div>
 <div class="row">
    <div class="col-lg-4">
    <h2>Receita 1</h2>
    <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
    <p><a class="btn btn-dark" href="#" role="button">View details &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
    <h2>Receita 2</h2>
    <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
    <p><a class="btn btn-dark" href="#" role="button">View details &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
    <h2>Receita 3</h2>
    <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
    <p><a class="btn btn-dark" href="#" role="button">View details &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
</div><!-- /.row -->

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>
<div class="row">
    <div class="col-md-12">
        <%= form_for(@recipe, :html => {class: "form-horizontal", role: "form"}) do |f|%>
            <div class="form-group">
                <div class="control-label col-md-2">
                    <%= f.label :name %>
                </div>
                <div class="col-md-8">
                    <%= f.text_field :name, class:"form-control", placeholder: "Name of recipe", autofocus: true%>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-2">
                    <%= f.label :description%>
                </div>
                <div class="col-md-8">
                    <%= f.text_area :description, rows:10, class:"form-control", placeholder:"Enter steps to create recipe"%>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <%= f.submit class:"btn btn-primary btn-lg btn-danger"%>
                </div>
            </div>
        <%end%>
        <div style="text-align: center">
            [ <%= link_to "Cancel request and return to recipes listing",recipes_path %> ]
        </div>
    </div>
</div>

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe| %>
  <div class="row">
    <div class="col-md-2">
      <section class="chef_info center">
        <%= gravatar_for(recipe.chef, size:110)%>
      </section>
    </div>
    <div class=" well col-md-8 bg-light">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= truncate(recipe.description, length: 150) %></p>
      <p>
        <span class="quiet"><small>Created 

        <%= time_ago_in_words(recipe.created_at) %> ago</small></span>
      </p> 
      <% if logged_in? && (current_chef == recipe.chef || current_chef.admin?)%>
        <div class="recipe-actions">
          <%= link_to "Edit this recipe", edit_recipe_path(recipe), class:"btn btn-xs btn-warning"%>
          <%= link_to "Delete this recipe", recipe_path(recipe), method: :delete, data: {confirm: "Are you sure you want to delete this recipe"},
                                      class: "btn btn-xs btn-danger"%>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title:"edit an existing recipe"%>
<%= render 'form'%>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title:'showing all recipes' %>
<div class="d-flex justify-content-center">
   <%= will_paginate @recipes, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer%>
</div>
<%= render 'recipe', obj: @recipes%>

<div class="d-flex justify-content-center">
  <%= will_paginate @recipes, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer%>
</div>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title:"create a new recipe"%>
<%= render 'form'%>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name%>
<div class="h-50 d-inline-block well col-md-8 col-md-offset-2 bg-light" style="margin-left:15%"> 
  <h4 class="center description"><strong>Steps: </strong></h4>
  <hr />
  <%= simple_format(@recipe.description )%>
  <hr />
  <div class="float-right">
    <p class="center">
      <em>Created by: </em>
    </p>
    <p class="center">
        <%= link_to gravatar_for(@recipe.chef), recipes_path%>
    </p>
    <p class="center">
        <small> <%= @recipe.chef.chefname.capitalize%> </small>
        <div class="float-right">
            <small> <%= time_ago_in_words(@recipe.created_at)%> ago</small>
        </div>
    </p>
  </div>
  <div class="recipe-actions">
    <% if logged_in? && (current_chef == @recipe.chef || current_chef.admin?)%>
      <%= link_to "Edit this recipe", edit_recipe_path(@recipe), class:"btn btn-xs btn-warning"%>
      <%= link_to "Delete this recipe", recipe_path(@recipe), method: :delete, data: {confirm: "Are you sure you want to delete this recipe"},
                                      class: "btn btn-xs btn-danger"%>
    <% end %>
    <%= link_to "Return to recipes list", recipes_path, class:"btn btn-xs btn-primary"%>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="card" id="error">
                <div class="card-header">
                    <h2 class= "card-title">
                        <%= pluralize(obj.errors.count, "error")%>
                        prohibted this <%= obj.class%> from being saved
                    </h2>
                    <div class="card-body">
                        <ul>
                            <% obj.errors.full_messages.each do |msg|%>
                                <li><%= msg %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/shared/_page_title.html.erb
<h1 align="center"><%= title.capitalize %></h1>
<hr />